import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppLayout } from "@/components/AppLayout";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Sparkles, Target, BookOpen, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/hooks/use-auth";
import {
  generateStudyPlan,
  getCurrentWeekTasks,
  toggleStudyTask,
} from "@/lib/study-plan.functions";

export const Route = createFileRoute("/study-plan")({
  head: () => ({
    meta: [
      { title: "Your Weekly Study Plan — Data Analyst Hub" },
      {
        name: "description",
        content: "AI-generated weekly study plan tailored to your progress, XP, and goals.",
      },
    ],
    links: [{ rel: "canonical", href: "/study-plan" }],
  }),
  component: StudyPlanPage,
});

function StudyPlanPage() {
  const { user } = useAuth();
  const qc = useQueryClient();
  const fetchTasks = useServerFn(getCurrentWeekTasks);
  const generate = useServerFn(generateStudyPlan);
  const toggle = useServerFn(toggleStudyTask);

  const { data, isLoading } = useQuery({
    queryKey: ["study-plan"],
    enabled: !!user,
    queryFn: () => fetchTasks(),
  });

  const generateMut = useMutation({
    mutationFn: () => generate(),
    onSuccess: () => {
      toast.success("Fresh plan generated!");
      qc.invalidateQueries({ queryKey: ["study-plan"] });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const toggleMut = useMutation({
    mutationFn: (vars: { id: string; done: boolean }) => toggle({ data: vars }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["study-plan"] }),
  });

  const tasks = data?.tasks ?? [];
  const done = tasks.filter((t) => t.done).length;
  const pct = tasks.length ? Math.round((done / tasks.length) * 100) : 0;

  return (
    <AppLayout>
      <div className="px-6 py-8 max-w-4xl mx-auto space-y-6">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Sparkles className="h-5 w-5 text-primary" />
              <h1 className="text-3xl font-bold gradient-text">Your weekly plan</h1>
            </div>
            <p className="text-sm text-muted-foreground">
              {data?.weekStart
                ? `Week of ${new Date(data.weekStart).toLocaleDateString()}`
                : "A personalized study plan, generated by your AI coach."}
            </p>
          </div>
          <Button
            onClick={() => generateMut.mutate()}
            disabled={!user || generateMut.isPending}
            className="bg-gradient-to-r from-primary to-accent"
          >
            {generateMut.isPending ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="h-4 w-4" />
            )}
            {tasks.length ? "Regenerate" : "Generate my plan"}
          </Button>
        </div>

        {!user && (
          <Card className="glass-card p-6 text-sm text-muted-foreground">
            <Link to="/login" className="text-primary hover:underline">Sign in</Link> to get a
            personalized weekly study plan.
          </Card>
        )}

        {user && tasks.length > 0 && (
          <Card className="glass-card p-5">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <Target className="h-4 w-4 text-primary" />
                <span className="text-sm font-medium">Weekly progress</span>
              </div>
              <Badge variant="outline">
                {done} / {tasks.length} done
              </Badge>
            </div>
            <Progress value={pct} />
          </Card>
        )}

        {user && isLoading && (
          <div className="text-center py-12 text-muted-foreground text-sm">
            <Loader2 className="h-5 w-5 animate-spin mx-auto mb-2" />
            Loading your plan…
          </div>
        )}

        {user && !isLoading && tasks.length === 0 && (
          <Card className="glass-card p-10 text-center space-y-3">
            <Sparkles className="h-10 w-10 text-primary mx-auto" />
            <h2 className="text-lg font-semibold">No plan yet for this week</h2>
            <p className="text-sm text-muted-foreground max-w-md mx-auto">
              Tap “Generate my plan” and your AI coach will craft a tailored set of tasks based on
              your XP, streak, and the courses you've explored.
            </p>
          </Card>
        )}

        <div className="space-y-3">
          {tasks.map((t) => (
            <Card key={t.id} className="glass-card p-4 flex gap-3 items-start">
              <Checkbox
                checked={t.done}
                onCheckedChange={(v) => toggleMut.mutate({ id: t.id, done: !!v })}
                className="mt-1"
              />
              <div className="flex-1 min-w-0">
                <p className={`font-medium ${t.done ? "line-through text-muted-foreground" : ""}`}>
                  {t.title}
                </p>
                {t.detail && (
                  <p className="text-sm text-muted-foreground mt-1 whitespace-pre-wrap">
                    {t.detail}
                  </p>
                )}
                {t.course_slug && (
                  <Button asChild variant="ghost" size="sm" className="mt-2 -ml-2 h-7 text-xs">
                    <Link to="/courses/$slug" params={{ slug: t.course_slug }}>
                      <BookOpen className="h-3 w-3" /> Open course
                    </Link>
                  </Button>
                )}
              </div>
            </Card>
          ))}
        </div>
      </div>
    </AppLayout>
  );
}
